# Built with Jekyll 3.2.0

# Setup
title:               Andrew Papenheim
tagline:             'Something to declare.'
description:         'Andrew studies governance and graphics. Finding better ways for states to communicate. Montrealer. Cheesehead. Cosmopolitan.'
url:                 'http://papenhe.im'
baseurl:             ''

# About/contact
author:
  name:              Andrew Papenheim
  url:               https://twitter.com/apapenheim
  email:             andrew@papenhe.im

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."